---
name: Setup Steampipe
description: >
  Install Steampipe and add it to the PATH. Optionally install plugins and create plugin connection configurations.
author: François de Metz and Turbot
branding:
  color: red
  icon: database
inputs:
  steampipe-version:
    description: 'Steampipe CLI version to install. Defaults to "latest". Examples: latest, 0.19.4, 0.20.8.'
    default: latest
    required: false
  plugin-connections:
    description: Steampipe plugin connections to create. Accepts HCL or JSON format.
    required: false
  steampipe-plugins:
    description: The plugins to install and configure.
    required: false
    deprecationMessage: This input will be removed in a future release. Please use plugin-connections instead.
outputs:
  steampipe-version:
    description: The version of Steampipe that was installed.
runs:
  using: node20
  main: dist/index.js
